package com.medsync.enums;

public enum Specialization {
	GENERAL_PHYSICIAN,CARDIOLOGIST,NEUROLOGIST,ENT_SPECIALIST,DENTIST,PULMONOLOGIST,RECEPTIONIST,OTHERS,GASTROENTEROLOGIST,PEDIATRICIAN,GYNECOLOGIST;
}
